### PR TITLE
OS X fixes for ARC release calls

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by ruslo** [comment]
@headupinclouds Thanks, what do you think about sending it to upstream? https://github.com/BradLarson/GPUImage

**Comment by headupinclouds** [comment]
Done.

**Comment by ruslo** [comment]
> Done

Cool, didn't noticed it :)

**Comment by headupinclouds** [comment]
That community might be interested in this effort.  CMake may arguably have less appeal for an Apple specific framework, but a single CMakelists.txt build option for generating both the iOS and OS X framework + sample app Xcode projects would still be quite useful.  It would be nice to host the handful of CMakeLists.txt files in the main repository at some point.  I'll bang on this a little more in my sandbox and then send them an email.

**Comment by ruslo** [comment]
@headupinclouds note that it doens't conflict with native Xcode project (i.e. you can hold both CMakeLists.txt and GPUImage.xcodeproj). So in general there are no problems (only when new file added you need to modify both *.xcodeproj and CMakeLists.txt)

**Pull request merged**
